### PR TITLE
Support for WMS Layer support

### PR DESCRIPTION
**Pull request by netmaxt3r**
### Does any other open PR do the same thing?

(please answer here)

### What issue is this PR fixing?
Add support for WMS Layer from geoserver 
https://docs.geoserver.org/latest/en/user/services/wms/reference.html

### How did you test this PR?

Tested on iOS simulator and device with Apple Maps and google maps
Android simulator and device samsung galaxy s8

### CODE REVIEW

**Comment by rborn** [comment]
LGTM (at a first glance) @alvelig 🐽

**Comment by shrikantkunte** [comment]
@netmaxt3r  I want to use WMSTiles, I [referred](https://github.com/react-community/react-native-maps/pull/2568/commits/01e518fa6044de30c94d5486a8b5367f9cb45c83#diff-890df05adf734db35328f6431430ad49) but it gives errors.
I am using the latest version v0.22.1. I think this version doesn't support WMSTiles. How can I integrate given [example](https://github.com/react-community/react-native-maps/pull/2568/commits/01e518fa6044de30c94d5486a8b5367f9cb45c83#diff-890df05adf734db35328f6431430ad49 ) in my application? Thanks in advance.

**Comment by andrey-shostik** [comment]
Why this PR still is not merged to master?

**Comment by rborn** [comment]
@andrey-shostik lack of time and resources, we could use some help in reviewing and testing the PRs 😉

**Comment by andrey-shostik** [comment]
I tested the example from this PR and this works well, but when I change urlTemplate, I can't find my Tile on map [myTemplate](https://polydon-gdeprozrak-geoserver-prod.gdeprozrak.teamcsrv.com/geoserver/clarity/wms?service=WMS&version=1.1.0&request=GetMap&layers=clarity:LC08_L1TP_129052_20190115_20190115_01_RT_Clarity_compressed&styles=&bbox=99.11044781418852,10.50871187944455,101.20201272844446,12.613659750190239&width=1000&height=1000&srs=EPSG:4326&format=image/png&transparent=true)
myCode 
```javascript
<WMSTile
  urlTemplate="https://polydon-gdeprozrak-geoserver-prod.gdeprozrak.teamcsrv.com/geoserver/clarity/wms?service=WMS&version=1.1.0&request=GetMap&layers=clarity:LC08_L1TP_148023_20190104_20190130_01_T1_Clarity_compressed&styles=&bbox={minX},{minY},{maxX},{maxY}&width={width}&height={height}&srs=EPSG:4326&format=image/png&transparent=true"
  zIndex={100}
  opacity={0.5}
  tileSize={512}
/>
```
What is wrong?

**Comment by christopherdro** [comment]
@netmaxt3r Thank you for this PR. I'd like to get this in for testing. Any chance you can resolve the small merge conflict?

**Comment by netmaxt3r** [comment]
> @netmaxt3r
> I have tested the example from PR and this works well, and with every layer from demo.geo-solutions.it geoserever too http://prntscr.com/n92brq, but when I change urlTemplate I can't find my Tile on map,
> My WMSTile: http://prntscr.com/naet63
> 
> ```js
> <WMSTile
>   urlTemplate="https://geoserver-url.com/geoserver/clarity/wms?service=WMS&version=1.1.0&request=GetMap&layers=clarity:LC08_L1TP_148023_20190104_20190130_01_T1_Clarity_compressed&styles=&bbox={minX},{minY},{maxX},{maxY}&width={width}&height={height}&srs=EPSG:4326&format=image/png&transparent=true"
>   zIndex={100}
>   opacity={0.5}
>   tileSize={512}
> />
> ```
> 
> Also I have tried to set urlTemplate with static coordinates, and after this it looks so: https://prnt.sc/n8z1rq
> I suppose that problem is in different EPSG, seems that register of my layer is EPSG:4326, just change it in urlTemplate to EPSG:900913 doesn't help.
> How to use EPSG:4326 here?
> What do you think?

aha seems like we need to support more spec, we need to implement methods for convert spec boundbox to map bound box. Current implementation [for ios](https://github.com/netmaxt3r/react-native-maps/blob/4f131adcf1567cd48bc5a2a8292e224ecc241c82/lib/ios/AirMaps/AIRMapWMSTile.m#L136) and [for android](https://github.com/netmaxt3r/react-native-maps/blob/4f131adcf1567cd48bc5a2a8292e224ecc241c82/lib/android/src/main/java/com/airbnb/android/react/maps/AirMapWMSTile.java#L53) is only for  EPSG:900913. I am not a wms expert but we can do some research and may be figure out bound box computation, which all specs should we support?

**Comment by andrey-shostik** [comment]
@netmaxt3r Thanks a lot for the answer, in my current project we really need support EPSG:4326.

**Comment by andrey-shostik** [comment]
@netmaxt3r so could you help in implementation boundbox for EPSG:4326? As I understand we just need to reimplement [ios](https://github.com/netmaxt3r/react-native-maps/blob/4f131adcf1567cd48bc5a2a8292e224ecc241c82/lib/ios/AirMaps/AIRMapWMSTile.m#L136) and for [android](https://github.com/netmaxt3r/react-native-maps/blob/4f131adcf1567cd48bc5a2a8292e224ecc241c82/lib/android/src/main/java/com/airbnb/android/react/maps/AirMapWMSTile.java#L53) getBoundBox method?

**Comment by netmaxt3r** [comment]
I am working on it , will try to complete in two days

**Comment by roquie** [comment]
Any news? :)

**Comment by netmaxt3r** [comment]
please check #2821 . I don't have much data to test it please provide your feedback

**Comment by andrey-shostik** [comment]
@netmaxt3r Hello, this is my code https://paste.ofcode.org/3b2KmZ47ks5iYctGxbH4JJ8
As well I have noticed another issue, when I use any wms tile with map provider google on ios, tile transparent doesn't work, and I don't see my map, only wihe background from tile.

**Comment by jmruvalcabav** [comment]
@andrey-shostik , this is the solution to the issue related to the transparent tile.

in AIRGoogleMapWMSTile:

- (UIImage *)tileForX:(NSUInteger)x y:(NSUInteger)y zoom:(NSUInteger)zoom
{
    NSInteger maximumZ = self.maximumZ;
    NSInteger minimumZ = self.minimumZ;
    if(maximumZ && (long)zoom > (long)maximumZ) {
        return nil;
    }
    if(minimumZ && (long)zoom < (long)minimumZ) {
        return nil;
    }
    NSArray *bb = [self getBoundBox:x yAxis:y zoom:zoom];
    NSMutableString *url = [self.template mutableCopy];
    [url replaceOccurrencesOfString: @"{minX}" withString:[NSString stringWithFormat:@"%@", bb[0]] options:0 range:NSMakeRange(0, url.length)];
    [url replaceOccurrencesOfString: @"{minY}" withString:[NSString stringWithFormat:@"%@", bb[1]] options:0 range:NSMakeRange(0, url.length)];
    [url replaceOccurrencesOfString: @"{maxX}" withString:[NSString stringWithFormat:@"%@", bb[2]] options:0 range:NSMakeRange(0, url.length)];
    [url replaceOccurrencesOfString: @"{maxY}" withString:[NSString stringWithFormat:@"%@", bb[3]] options:0 range:NSMakeRange(0, url.length)];
    [url replaceOccurrencesOfString: @"{width}" withString:[NSString stringWithFormat:@"%d", (int)self.tileSize] options:0 range:NSMakeRange(0, url.length)];
    [url replaceOccurrencesOfString: @"{height}" withString:[NSString stringWithFormat:@"%d", (int)self.tileSize] options:0 range:NSMakeRange(0, url.length)];
    NSURL *uri =  [NSURL URLWithString:url];
    NSData *data = [NSData dataWithContentsOfURL:uri];
    UIImage *img = [[UIImage alloc] initWithData:data];
    CGSize size = [img size];
    UIGraphicsBeginImageContext(size);
    CGRect rect = CGRectMake(0, 0, size.width, size.height);
    [img drawInRect:rect blendMode:kCGBlendModeNormal alpha:1.0];
    CGContextRef context = UIGraphicsGetCurrentContext();
    CGContextSetRGBStrokeColor(context, 0.0, 0.0, 0.0, 0.0);
    CGContextSetLineWidth(context, 5.0);
    CGContextStrokeRect(context, rect);
    UIImage *fixedImage =  UIGraphicsGetImageFromCurrentImageContext();
    UIGraphicsEndImageContext();
    return fixedImage;
}

**Comment by vnlebaoduy** [comment]
@netmaxt3r  I cant find WMSTile in version 0.24.2 . How to test this PR

**Comment by tunm1228** [comment]
> @netmaxt3r I cant find WMSTile in version 0.24.2 . How to test this PR. Thank so much

I also have problems like you

**Comment by 100phel** [comment]
I tried the example `https://github.com/react-native-community/react-native-maps/blob/master/example/examples/WMSTiles.js` and it fails with the message: 

`ExceptionsManager.js:82 Invariant Violation: Invariant Violation: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.

Check the render method of `WMSTiles`.
`

**Comment by 100phel** [comment]
My tile server requires an authentication header to be added to the request:
'var client = new XMLHttpRequest();

client.open('GET', src, true);
client.setRequestHeader('Authorization', "Basic " + authorization_encoded);'

Is there any place I can add it in the WMSTile ?

**Pull request merged**
