### PR TITLE
rn 0.60.5 support

### PR DESCRIPTION
**Pull request by jgtoriginal**
`react-native 0.60.5 - package android.support.v4.content does not exist`

### CODE REVIEW

**Comment by DavidPineda** [comment]
Hi @jgtoriginal, I have that same change and it generates this error.
 
https://github.com/react-native-community/react-native-maps/issues/2495

Do you have the library with autolink?

**Comment by cipriancaba** [comment]
Have you tried using `jetify` in a `postinstall` in `package.json`? That should fix your issue and it's how older libraries are being transitioned to AndroidX

**Comment by matinzd** [comment]
Any release on these pull requests?!??!? Last release is for month ago !

**Comment by jgtoriginal** [comment]
I can confirm that following @cipriancaba suggestion on the main project (the one that requires this module) sorts things out. Which puts us in a chicken and an egg situation.
Because if we think that this library should support RN 0.60 out of the box without needing further configurations on the host project in order to work, then this PR should be merged to master, no doubt.
But if we think that there are many users still on RN =< 0.59, merging this would brake their projects and force them to upgrade to RN 0.60 and go for `jetify` for other modules. Which will eventually happen, maybe not just yet.

**Comment by salah-ghanim** [comment]
@jgtoriginal this library should support the latest RN version. users with lower RN versions don't have to update.

**Comment by paolorovella** [comment]
@aurangzaib @jgtoriginal any news on this? `react-native` was updated to `v0.61.1` so i think it's time to merge this PR 🙂

**Pull request merged**
