### PR TITLE
Fix Android dependencies and build errors

### LINKED ISSUE #2663: Could not resolve all files for configuration ':react-native-maps:debugCompileClasspath'.
### Is this a bug report?

Yes, The linking to react-native is successful but fails to run the project

### Have you read the [Installation Instructions](https://github.com/react-community/react-native-maps/blob/master/docs/installation.md)?

Yes, I have read all the instructions and followed them as well.

### Environment
"react": "16.6.1",
"react-native": "0.57.6",
"react-native-maps": "^0.22.1",

### Steps to Reproduce

(Write your steps here:)

1. On running the command "react-native run-android", The following errors are encountered in the terminal:

Could not resolve com.android.support:support-annotations:24.0.0.
  Required by:
      project :react-native-maps > com.android.support:support-v4:24.0.0
   > Cannot find a version of 'com.android.support:support-annotations' that satisfies the version constraints:

Could not resolve com.android.support:support-annotations:27.1.1.
  Required by:
      project :react-native-maps > com.facebook.react:react-native:0.57.6 > com.android.support:appcompat-v7:27.1.1

### Expected Behavior
Should have compiled successfully

(Write what you thought would happen.)

### Actual Behavior
 The above mentioned errors are logged in the console and the app doesn't start successfully.

(Write what happened. Add screenshots!)
> Configure project :react-native-firebase
react-native-firebase: using React Native prebuilt binary from /Users/vishesh/learning/xemo-local-app/node_modules/react-native/android

> Task :react-native-maps:compileDebugRenderscript FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Could not resolve all files for configuration ':react-native-maps:debugCompileClasspath'.
> Could not resolve com.android.support:support-annotations:24.0.0.
  Required by:
      project :react-native-maps
   > Cannot find a version of 'com.android.support:support-annotations' that satisfies the version constraints:
        Dependency path 'xempAppNew:react-native-maps:unspecified' --> 'com.facebook.react:react-native:0.57.6' --> 'com.android.support:appcompat-v7:27.1.1' --> 'com.android.support:support-annotations:27.1.1'
        Dependency path 'xempAppNew:react-native-maps:unspecified' --> 'com.facebook.react:react-native:0.57.6' --> 'com.android.support:appcompat-v7:27.1.1' --> 'com.android.support:support-core-utils:27.1.1' --> 'com.android.support:support-annotations:27.1.1'
        Dependency path 'xempAppNew:react-native-maps:unspecified' --> 'com.facebook.react:react-native:0.57.6' --> 'com.android.support:appcompat-v7:27.1.1' --> 'com.android.support:support-fragment:27.1.1' --> 'com.android.support:support-annotations:27.1.1'
        Dependency path 'xempAppNew:react-native-maps:unspecified' --> 'com.facebook.react:react-native:0.57.6' --> 'com.android.support:appcompat-v7:27.1.1' --> 'com.android.support:support-vector-drawable:27.1.1' --> 'com.android.support:support-annotations:27.1.1'
        Dependency path 'xempAppNew:react-native-maps:unspecified' --> 'com.google.android.gms:play-services-base:10.2.4' --> 'com.google.android.gms:play-services-basement:10.2.4' --> 'com.android.support:support-v4:24.0.0' --> 'com.android.support:support-annotations:24.0.0'
        Dependency path 'xempAppNew:react-native-maps:unspecified' --> 'com.facebook.react:react-native:0.57.6' --> 'com.android.support:appcompat-v7:27.1.1' --> 'com.android.support:support-core-utils:27.1.1' --> 'com.android.support:support-compat:27.1.1' --> 'com.android.support:support-annotations:27.1.1'
        Dependency path 'xempAppNew:react-native-maps:unspecified' --> 'com.facebook.react:react-native:0.57.6' --> 'com.android.support:appcompat-v7:27.1.1' --> 'com.android.support:support-fragment:27.1.1' --> 'com.android.support:support-core-ui:27.1.1' --> 'com.android.support:support-annotations:27.1.1'
        Constraint path 'xempAppNew:react-native-maps:unspecified' --> 'com.android.support:support-annotations' strictly '24.0.0' because of the following reason: debugRuntimeClasspath uses version 24.0.0
        Constraint path 'xempAppNew:react-native-maps:unspecified' --> 'com.android.support:support-annotations' strictly '24.0.0' because of the following reason: debugRuntimeClasspath uses version 24.0.0

> Could not resolve com.android.support:support-annotations:27.1.1.
  Required by:
      project :react-native-maps > com.facebook.react:react-native:0.57.6 > com.android.support:appcompat-v7:27.1.1
      project :react-native-maps > com.facebook.react:react-native:0.57.6 > com.android.support:appcompat-v7:27.1.1 > com.android.support:support-core-utils:27.1.1
      project :react-native-maps > com.facebook.react:react-native:0.57.6 > com.android.support:appcompat-v7:27.1.1 > com.android.support:support-fragment:27.1.1
      project :react-native-maps > com.facebook.react:react-native:0.57.6 > com.android.support:appcompat-v7:27.1.1 > com.android.support:support-vector-drawable:27.1.1
      project :react-native-maps > com.facebook.react:react-native:0.57.6 > com.android.support:appcompat-v7:27.1.1 > com.android.support:support-core-utils:27.1.1 > com.android.support:support-compat:27.1.1
      project :react-native-maps > com.facebook.react:react-native:0.57.6 > com.android.support:appcompat-v7:27.1.1 > com.android.support:support-fragment:27.1.1 > com.android.support:support-core-ui:27.1.1
   > Cannot find a version of 'com.android.support:support-annotations' that satisfies the version constraints:
        Dependency path 'xempAppNew:react-native-maps:unspecified' --> 'com.facebook.react:react-native:0.57.6' --> 'com.android.support:appcompat-v7:27.1.1' --> 'com.android.support:support-annotations:27.1.1'
        Dependency path 'xempAppNew:react-native-maps:unspecified' --> 'com.facebook.react:react-native:0.57.6' --> 'com.android.support:appcompat-v7:27.1.1' --> 'com.android.support:support-core-utils:27.1.1' --> 'com.android.support:support-annotations:27.1.1'
        Dependency path 'xempAppNew:react-native-maps:unspecified' --> 'com.facebook.react:react-native:0.57.6' --> 'com.android.support:appcompat-v7:27.1.1' --> 'com.android.support:support-fragment:27.1.1' --> 'com.android.support:support-annotations:27.1.1'
        Dependency path 'xempAppNew:react-native-maps:unspecified' --> 'com.facebook.react:react-native:0.57.6' --> 'com.android.support:appcompat-v7:27.1.1' --> 'com.android.support:support-vector-drawable:27.1.1' --> 'com.android.support:support-annotations:27.1.1'
        Dependency path 'xempAppNew:react-native-maps:unspecified' --> 'com.google.android.gms:play-services-base:10.2.4' --> 'com.google.android.gms:play-services-basement:10.2.4' --> 'com.android.support:support-v4:24.0.0' --> 'com.android.support:support-annotations:24.0.0'
        Dependency path 'xempAppNew:react-native-maps:unspecified' --> 'com.facebook.react:react-native:0.57.6' --> 'com.android.support:appcompat-v7:27.1.1' --> 'com.android.support:support-core-utils:27.1.1' --> 'com.android.support:support-compat:27.1.1' --> 'com.android.support:support-annotations:27.1.1'
        Dependency path 'xempAppNew:react-native-maps:unspecified' --> 'com.facebook.react:react-native:0.57.6' --> 'com.android.support:appcompat-v7:27.1.1' --> 'com.android.support:support-fragment:27.1.1' --> 'com.android.support:support-core-ui:27.1.1' --> 'com.android.support:support-annotations:27.1.1'
        Constraint path 'xempAppNew:react-native-maps:unspecified' --> 'com.android.support:support-annotations' strictly '24.0.0' because of the following reason: debugRuntimeClasspath uses version 24.0.0
        Constraint path 'xempAppNew:react-native-maps:unspecified' --> 'com.android.support:support-annotations' strictly '24.0.0' because of the following reason: debugRuntimeClasspath uses version 24.0.0

> Could not resolve com.android.support:support-annotations:24.0.0.
  Required by:
      project :react-native-maps > com.android.support:support-v4:24.0.0
   > Cannot find a version of 'com.android.support:support-annotations' that satisfies the version constraints:
        Dependency path 'xempAppNew:react-native-maps:unspecified' --> 'com.facebook.react:react-native:0.57.6' --> 'com.android.support:appcompat-v7:27.1.1' --> 'com.android.support:support-annotations:27.1.1'
        Dependency path 'xempAppNew:react-native-maps:unspecified' --> 'com.facebook.react:react-native:0.57.6' --> 'com.android.support:appcompat-v7:27.1.1' --> 'com.android.support:support-core-utils:27.1.1' --> 'com.android.support:support-annotations:27.1.1'
        Dependency path 'xempAppNew:react-native-maps:unspecified' --> 'com.facebook.react:react-native:0.57.6' --> 'com.android.support:appcompat-v7:27.1.1' --> 'com.android.support:support-fragment:27.1.1' --> 'com.android.support:support-annotations:27.1.1'
        Dependency path 'xempAppNew:react-native-maps:unspecified' --> 'com.facebook.react:react-native:0.57.6' --> 'com.android.support:appcompat-v7:27.1.1' --> 'com.android.support:support-vector-drawable:27.1.1' --> 'com.android.support:support-annotations:27.1.1'
        Dependency path 'xempAppNew:react-native-maps:unspecified' --> 'com.google.android.gms:play-services-base:10.2.4' --> 'com.google.android.gms:play-services-basement:10.2.4' --> 'com.android.support:support-v4:24.0.0' --> 'com.android.support:support-annotations:24.0.0'
        Dependency path 'xempAppNew:react-native-maps:unspecified' --> 'com.facebook.react:react-native:0.57.6' --> 'com.android.support:appcompat-v7:27.1.1' --> 'com.android.support:support-core-utils:27.1.1' --> 'com.android.support:support-compat:27.1.1' --> 'com.android.support:support-annotations:27.1.1'
        Dependency path 'xempAppNew:react-native-maps:unspecified' --> 'com.facebook.react:react-native:0.57.6' --> 'com.android.support:appcompat-v7:27.1.1' --> 'com.android.support:support-fragment:27.1.1' --> 'com.android.support:support-core-ui:27.1.1' --> 'com.android.support:support-annotations:27.1.1'
        Constraint path 'xempAppNew:react-native-maps:unspecified' --> 'com.android.support:support-annotations' strictly '24.0.0' because of the following reason: debugRuntimeClasspath uses version 24.0.0
        Constraint path 'xempAppNew:react-native-maps:unspecified' --> 'com.android.support:support-annotations' strictly '24.0.0' because of the following reason: debugRuntimeClasspath uses version 24.0.0

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 5.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/4.10.1/userguide/command_line_interface.html#sec:command_line_warnings

BUILD FAILED in 8s

### PR DESCRIPTION
**Pull request by friederbluemle**
### Does any other open PR do the same thing?

No

### What issue is this PR fixing?

Currently, the yarn tasks `start:android` and `run:android` to build and run the Android version are failing on the `master` branch with the following error:

```
* What went wrong:
A problem occurred evaluating project ':react-native-maps-lib'.
> Could not find method compileOnly() for arguments [com.facebook.react:react-native:+] on object of type org.gradle.api.internal.artifacts.dsl.dependencies.DefaultDependencyHandler.
```

This is caused by partially and incorrectly updated dependencies of the Android build system, which was addressed by updating the dependencies as described below. Many obsolete and unused leftover files of old Gradle wrapper installations and a couple of files from the Eclipse days were removed as well.

The three main things this PR addresses is:

- Update Gradle wrapper to 5.2.1 (latest stable version)
- Update Android Gradle plugin to 3.2.1 (version that ships with latest version of React Native)
- Remove unused `appcompat-v7` dependency from library project

See individual commits for more details.

### How did you test this PR?

    react-native start
    yarn run-android
    yarn run-ios

Correct behavior (build and run) was verified using an Android device, an Android emulator, and an iOS simulator.

Includes and closes #2712
Also fixes #2663

<sub><sup>Once approved, please use a *normal* GitHub merge (i.e. **NO rebase/squash** merge) to integrate the commit(s) from the branch of this pull request. The changes are broken up into meaningful, [atomic commits](https://www.freshconsulting.com/atomic-commits/), and my branch should already be up-to-date with the latest target branch. If it isn't, or if you'd like me to combine something, please let me know, and I will make the necessary updates as soon as possible. Thank you!</sup></sub>

### CODE REVIEW

**Comment by alvelig** [comment]
LGTM @rborn 🐽

**Comment by radeno** [comment]
@friederbluemle 
I like this PR, when i created first PR for react-native-maps it was pain for me to run test environment. Almost everything was outdated and not working. So i am welcoming it.

What i recommend by mine good practice is to separate iOS and Android specific changes as two PRs. It could be checked and tested separately. This PR is not change in couple files, but 26. It could helps to merge it faster when it will be as two independent pull requests.

Do you think use Gradle 5.2.x is good idea? RN 0.58 uses 4.10.2, even RN0.59 will use 4.2. Gradle 5.0 lands in RN master branch just 12 days ago. I think 4.10 is safe now.
Why was removed `gradle-wrapper.jar` ?

**Comment by radeno** [comment]
Anyway iOS changes looks good to me.
All chagnes are created by Cocoapods automatic scripts. So its safe.

**Comment by friederbluemle** [comment]
@radeno - Thanks a lot for the review and the comment! 👍 

As you suggested, I downgraded the Gradle wrapper to `4.10.3` (like you said, RN currently ships with the 4.10.x version)

I also excluded the ios changes (Podfile.lock) - I'll open a separate PR once this one is in. It should make the review a bit easier.

**Comment by radeno** [comment]
@friederbluemle i'm not an Android expert so lets get inspiration from https://github.com/react-native-community/react-native-netinfo which was community repo from other community repos taking inspiration in Lean Core initiative.

All gradle files from root folder should be deleted or moved to right place. We need only related for build in `lib/android` and example directory `example/android`, It is little bit mess, because gradle config files are not separated by scope "build" or "example". Be we have third scope, global. Which is what you don't bring with this PR, it is existed legacy. So lets clean it up.

Can you check it please?

**Comment by friederbluemle** [comment]
@radeno - Yes good point. Do you suggest we should also do it in this PR as well or do keep it separate? As you mentioned I am not introducing any new legacy tech debt with this PR (only clean up, removing files, and updating/moving _existing_ files).

I agree there is more follow up work to be done. I have some pending wip on a separate branch locally that _moves_ the wrapper from the root directory (I think that should be taken care of separately).

**Comment by radeno** [comment]
@friederbluemle in my opinion it should be good move to transfer them into correct directories by this PR. 
Running examples on actual Android studio is broken anyway without your PR. And removing global Gradle scope is nice to have.

Most gradle files from root directory belongs to example directory. So i think, yes lets move it.

**Comment by friederbluemle** [comment]
@radeno - To make the PR review easier and lower the impact/risk, would it be possible to use _two_ PRs? This PR here does not _create_ any new files, just updates existing ones. I will open a follow up PR right after this on is in. We are already successfully using an internal fork with the changes on this PR.

**Comment by radeno** [comment]
@fiederbluemle for me it doesnt matter because test case is easy. Will it work or will not :) but i am not maintaner.
Cc @alvelig @rborn

**Comment by alvelig** [comment]
LGTM @rborn @christopherdro @salah-ghanim

**Comment by rborn** [comment]
@alvelig @christopherdro @salah-ghanim LGTM

**Comment by grifotv** [comment]
@friederbluemle unfortunately I'm unable to run `react-native run-android` since this has been merged.

```
info Building and installing the app on the device (cd android && ./gradlew app:installDebug)...

> Configure project :app
Reading env from: .env.development

FAILURE: Build failed with an exception.

* Where:
Script '/my_project_path/node_modules/react-native-maps/lib/android/gradle-maven-push.gradle' line: 48

* What went wrong:
A problem occurred configuring project ':react-native-maps'.
> Could not get unknown property 'GROUP' for object of type org.gradle.api.publication.maven.internal.deployer.DefaultGroovyMavenDeployer.

```

- `react-native`: `next`
- `react-native-maps`: `https://github.com/react-community/react-native-maps.git`

Should I create an issue?

Thanks

**Comment by friederbluemle** [comment]
@grifotv Thanks for the report. I'm checking now!

**Comment by friederbluemle** [comment]
Confirming the build error that @grifotv reported.

I missed including a small change in this PR that I had locally. Sorry about that.

I opened a PR with the fix here: #2727

@christopherdro @alvelig @rborn - Please check, hopefully we can get this merged quickly. Thanks and sorry again for the oversight!

**Comment by alvelig** [comment]
Merged

**Comment by rborn** [comment]
@friederbluemle it looks like some people still have issues with a missing line in build.gradle
`implementation "com.android.support:appcompat-v7:${rootProject.ext.supportLibVersion}"`

https://github.com/react-native-community/react-native-maps/issues/2695#issuecomment-473205914


This PR only includes it in example, but not in the `lib/android/build.gradle`

Do we need to add it there or they are using an older version of the module? ( didn't have time to test :( )
Thanks

**Comment by friederbluemle** [comment]
@rborn Thanks for the heads up! Looking into it!

**Comment by friederbluemle** [comment]
@rborn - Looking at the comments in the other thread, these people were not using the `master` branch of `react-native-maps` (i.e. the `build.gradle` file posted looks different than the one currently on `master`).

I checked the code again, and there are definitely **no dependencies** on `appcompat-v7` in the library project.

However, there are a couple of dependencies on `android.support.v4` in `AirMapView`. So, technically `support-v4` _should_ explicitly be declared as a dependency in `build.gradle`. For now, it's probably best to re-add `appcompat-v7`. See #2743.
Note that `support-v4` is also pulled in transitively by many other libraries, for example `play-services-base`:

```
$ ./gradlew :react-native-maps-lib:dependencies

[...]
+--- com.google.android.gms:play-services-base:16.1.0
|    +--- com.google.android.gms:play-services-basement:16.2.0
|    |    \--- com.android.support:support-v4:26.1.0
[...]
```

The issues people are having are most likely related to the way dependencies are declared in the app project, and the resulting conflicts.

Other possible solutions/workarounds include:

```
    implementation ('com.facebook.react:react-native:+') {
        exclude group: 'com.android.support', module: 'support-v4'
    }
```

or

```
subprojects {
  project.configurations.all {
    resolutionStrategy.eachDependency { details ->
      if (details.requested.group == 'com.android.support'
          && details.requested.name == 'support-v4') {
        details.useVersion '28.0.0'
      }
    }
  }
}
```

Ideally there should be no need to modify files inside of the `node_modules` folder!

**Comment by rborn** [comment]
@friederbluemle thank you very much for the investigation. Let's keep it like his for now and keep an  eye on it.
I expect to upgrade a project to last RN soon so I'll also test first hand.

Thanks again ❤️

**Comment by arosendorff** [comment]
Sorry if I missed it, but is there a reason why this PR takes out the ability of react-native-maps to use the googlePlayServicesVersion in your top level gradle file?

**Comment by friederbluemle** [comment]
@arosendorff - Good question!

The library (and its source code) is built against and guaranteed to work with _one specific version_ of the `play-services-*` artifacts. The same is true for all other dependencies. Therefore, making it possible to _externally_ modify the dependency versions used (without looking and checking the source code) leads to brittle and unpredictable builds.

**However**: It _does_ seem like this unfortunately is the prevalent, "recommended", and only (?) way dependencies of React Native apps are handled, at least at the moment.
In many cases, "small" updates (i.e. the patch component) will work without issues and don't require code updates. I assume the main reason for the desire to set this externally is to avoid certain types of dependency mismatch errors during the build. Being able to adjust the versions with the `ext` variables offers a "simple" solution to align transitive dependencies used by several referenced packages, though there is no guarantee it will work, and there are other ways to prevent mismatch errors as well.

In any case, I do admit this was a mistake on my end, and it's not the job of this repository/library to change the way React Native dependencies are consumed, so I've added this functionality back in this PR right here: #2765

**Comment by rborn** [comment]
@arosendorff #2765 was merged, please test with the last master. Thanks for your observation 🤗

**Comment by arosendorff** [comment]
@friederbluemle I get what you're saying about the built again `play-services-*` artifacts. Perhaps it's worth mentioning in the readme that while the module will honour your global configuration, there is a recommended version you should use to ensure everything runs smoothly?

@rborn Perfect, thanks so much! 🙂

**Comment by termux-io** [comment]
`[b7cba7d16163076ce3a7b2af1fd9e57731eb53a7](https://changelogs.online)`

**Comment by appli-intramuros** [comment]
Hello !

Since this PR is merged, the build gradle parameter: **androidMapsUtilsVersion** is not use anymor. (the commit: https://github.com/react-native-maps/react-native-maps/pull/2720/commits/8811ba3340b4261bc89a4f6d435b78d21e291001).

Is it normal ?

**Comment by friederbluemle** [comment]
> Hello !
> 
> Since this PR is merged, the build gradle parameter: **androidMapsUtilsVersion** is not use anymore. (the commit: [8811ba3#diff-c6899e54b9ed67b2d9034a841311198095bc6419675fc9f59874312c341fe414L59](https://github.com/react-native-maps/react-native-maps/commit/8811ba3340b4261bc89a4f6d435b78d21e291001#diff-c6899e54b9ed67b2d9034a841311198095bc6419675fc9f59874312c341fe414L59)).
> 
> Is it normal ?

Hi @appli-intramuros - Yes, this is normal. If you require a different version of the dependency, you could try Gradle dependency substitution (only works for versions that are backwards compatible) - or - (preferred) submit a PR to this repo and update to the latest version.

**Pull request merged**
