### PR TITLE
Implement onUserLocationChange in AIRMap

### PR DESCRIPTION
**Pull request by troZee**
(please answer here)

### What issue is this PR fixing?

Resolved https://github.com/react-native-community/react-native-maps/issues/2055

### How did you test this PR?

Changes was made in iOS/Apple maps and tested only on ip7 iOS 11

### CODE REVIEW

**Comment by ptrocki** [comment]
cc @rborn

**Comment by rborn** [comment]
@ptrocki looks good, let me find a little time to test on iOS 12 and I'll come back yo you ❤️

**Comment by smallsaucepan** [comment]
@ptrocki - found this PR while looking at heading component of user location. Was there a particular reason heading was not included? If not, I will add in subsequent PR.

**Comment by ptrocki** [comment]
Can you describe, what is heading ?

**Comment by smallsaucepan** [comment]
Sure thing. Heading or bearing, as in the compass direction.

**Comment by ptrocki** [comment]
I just forgot to add it. You can create a separate PR for it.

**Comment by ssztemberg** [comment]
I just checked that on iOS 13.1, iPhone X and it works fine. Don't forget to change readme `Make sure showsUserLocation is set to true and that the provider is "google".`

**Comment by rborn** [comment]
@troZee can you please fix conflicts and I'll merge ❤️

**Comment by troZee** [comment]
@rborn done

**Comment by ssztemberg** [comment]
@troZee You should also change readme, now it mentions that this is only for Google.

**Comment by rborn** [comment]
@troZee @ssztemberg ❤️

**Pull request merged**
