### PR TITLE
Bugfix for the "require cycles" warning

### PR DESCRIPTION
**Pull request by myty**
### Does any other open PR do the same thing? 

No

### What issue is this PR fixing?

#3352 

### How did you test this PR?

I verified that I no longer get the warning messages in the console. I was only able to test this on an android emulator, but its a pretty minimal javascript change, so I would assume it would work on iOS as well.

### CODE REVIEW

**Comment by ziyaddin** [comment]
@rborn is it possible to publish new version? This error breaks map rendering.

**Comment by charleycesar** [comment]
I'm waiting for this fix too.

**Comment by Pat-Gekoski** [comment]
This is a pretty important library for my app. I can use patch-package but I'd rather just have this fix published.....time-frame?

**Comment by arafatzahan** [comment]
Need a npm update with this merged

**Comment by stephen776** [comment]
Can we get this released to NPM?

**Comment by andersonaddo** [comment]
Yo can we get this published please 😂
giphy

**Comment by kuasha420** [comment]
We'll never get another release for this :/

**Comment by KrisLau** [comment]
I just tested this with the latest release of 0.28.0 and I still get the error
image

**Pull request merged**
