### PR TITLE
android google map callout support <Image/>

### PR DESCRIPTION
**Pull request by dkleikesa**
### Does any other open PR do the same thing?

NO

### What issue is this PR fixing?

https://github.com/react-native-community/react-native-maps/issues/2633

### How did you test this PR?

Use the example page  [Arbitrary Views as Markers] , wait a little time, and tap the bear marker

### CODE REVIEW

**Comment by orhan** [comment]
Any ETA on when this will be tested/merged?
Can I help with something to fasten up the process?

**Comment by thanhluantl2304** [comment]
> Any ETA on when this will be tested/merged?
> Can I help with something to fasten up the process?

I'm still waiting for it too. Don't know why it had taken a long time

**Comment by jeremybviseo** [comment]
Same issue, fix works for me, why it was not merged ?

**Comment by Eramirez06** [comment]
why this is nor merge yet?

**Comment by artmare** [comment]
If it works. Why it not merged? Please, merge it!

**Comment by DanLeCornu** [comment]
please merge!

**Comment by amsimoes** [comment]
MERGE it please !!! 👍 👍 👍 👍 👍

**Comment by johnhaup** [comment]
Does this repo need help with maintainers?

**Comment by rborn** [comment]
@johnhaup any help is more than welcome :)

**Comment by rborn** [comment]
LGTM @christopherdro @alvelig  🐽

**Comment by AndreBordignon** [comment]
Pls merge! Thank you

**Comment by DanLeCornu** [comment]
Thank you for merging, however, I pulled the latest and it's still not working for me, am i missing something? Is anyone else getting the same issue still?

## 🐛 Bug Report

### Package version
0.26.1

### Steps to Reproduce
Add an Image component within the Callout component, and it's failing to render, only fails to render for Android, iOS works fine.

### Expected Behavior
That the image renders in both Android and iOS

### Actual Behavior
Image does not render in Android

### Reproducible Demo
https://snack.expo.io/HJFqIAsVU

**Comment by christopherdro** [comment]
These changes have been reverted. Please see discussion in #3035

**Comment by piotrgomola** [comment]
@christopherdro why these changes were reverted? 

In my case the image issue on Android was solved in 0.27.0.

**Comment by rpadilla6** [comment]
@piotrgomola It's possible the fix worked for some, but as for @DanLeCornu and I it did not. For the meantime I had to resort to doing the [Text wrapper fix](https://github.com/react-native-community/react-native-maps/issues/2633#issuecomment-524324731). Hoping a consistent fix gets added in though, current workarounds are less than ideal.

**Comment by dkleikesa** [comment]
> Thank you for merging, however, I pulled the latest and it's still not working for me, am i missing something? Is anyone else getting the same issue still?
> 
> ## 🐛 Bug Report
> ### Package version
> 0.26.1
> 
> ### Steps to Reproduce
> Add an Image component within the Callout component, and it's failing to render, only fails to render for Android, iOS works fine.
> 
> ### Expected Behavior
> That the image renders in both Android and iOS
> 
> ### Actual Behavior
> Image does not render in Android
> 
> ### Reproducible Demo
> https://snack.expo.io/HJFqIAsVU

You may need add this prop 'tracksViewChanges={true}'

**Comment by dkleikesa** [comment]
> These changes have been reverted. Please see discussion in #3035
> @dkleikesa Can you take a look?

I tested it and it works fine, you may need to add this configuration 'tracksViewChanges={true}'

**Comment by DanLeCornu** [comment]
thanks! will test it out asap

**Comment by ilchoTaleski** [comment]
I tried https://github.com/dragma/react-native-maps.git#BOUYA and version 0.27.1 and Image is still not showing on Android. Also Text wrapping was not working for me. Can someone help on this one?

**Comment by ilchoTaleski** [comment]
> I tried https://github.com/dragma/react-native-maps.git#BOUYA and version 0.27.1 and Image is still not showing on Android. Also Text wrapping was not working for me. Can someone help on this one?

Okay, wrapping with Text was not working because of flex, now I managed to fix it with static width and height, but it would be good if this is fixed and Image is supported.

**Pull request merged**
