### PR TITLE
Added option for calloutContentViewInset to customize padding of callout

### PR DESCRIPTION
**Pull request by olofd**
Adds ability to set a or override the default (12, 12, 12, 12) calloutContentViewInset.
This way you can have a bubble without padding.

### CODE REVIEW

**Comment by olofd** [comment]
By enabling this, markers can look like this:
[marker]: https://imgur.com/a/jPUfu "Marker with negative contentInset"

**Comment by alvelig** [comment]
@rborn 🐽 
@allthetime thanks for the reminder. Worth mentioning that it's only for iOS

**Comment by rborn** [comment]
@olofd or @allthetime could you please add  the needed docs? 
Thank you :)

**Comment by rborn** [comment]
Closing as being an old issue and not a clear reply. Thanks for all the effort 😻

**Pull request closed without merging**
