### PR TITLE
marker icon is scalable now,needs width and height in marker props

### PR DESCRIPTION
**Pull request by shashi080195**
### Does any other open PR do the same thing?
no

### What issue is this PR fixing?
#733 

### How did you test this PR?
i have tested it in my application on mobiles of different api versions
- Which platform (eg. Android/iOS) & Maps API (eg. Google/Apple) does this change affect, if any?Andorid
- Did you test this on a real device, or in a simulator?
I have tested it a real device
- Are there any platforms you were not able to test?
no

### CODE REVIEW

**Comment by chakrihacker** [comment]
Any update on this??

**Comment by oliverdolgener** [comment]
Can someome please review this. It would be really helpful to have reliable custom icon sizes for markers on Android and iOS.

**Comment by dakairus** [comment]
any update on this, it would solve a issue I currently got on small screen devices

**Comment by stockrel** [comment]
+1

**Comment by alvelig** [comment]
LGTM. Though not sure about the performance.
And of course missing iOS version.
@rborn 🐽

**Comment by rborn** [comment]
@alvelig I'm worried about performance too.
On the other side we should not merge non cross-platform features unless they are specific to one platform only.

**Comment by shashi080195** [comment]
will update with the ios version also

**Comment by chakrihacker** [comment]
We are using with 10 - 20 markers, I haven't seen any performance regression.

**Comment by andreencar** [comment]
@shashi080195 any news about the ios fix?

**Comment by jramalho** [comment]
having some issues with Marker icon on iPhone, to have the same size on android you need to / by the DPI  ratio on the original image.

**Comment by rborn** [comment]
@chakrihacker 20 markers are not much, what about 200 or more?

**Comment by rborn** [comment]
Closing as being an old PR and not a clear reply. Thanks for all the effort 😻

**Pull request closed without merging**
