### PR TITLE
Support TMS for TileUrl

### PR DESCRIPTION
**Pull request by LeMinh1995**
### Does any other open PR do the same thing?

No

### What issue is this PR fixing?

The map will render the map imagery incorrectly as using a TMS URL.

### How did you test this PR?

(please answer here)

### CODE REVIEW

**Comment by LeMinh1995** [comment]
Hi sir, currently, I'm working with TileUrl component. Everything goes well until I tried to get imagery from a server that has the folder structure of TMS. The imagery is displayed incorrectly vertically, so I have made some changes to support for TMS. To use the TMS scheme, we need to replace {y} with {y-tms}. Please, have a look and give me your thinking about it. Thanks in advanced.

**Comment by reilem** [comment]
Your solution for iOS MapKit seems a little over complex. You can simply add `self.tileOverlay.geometryFlipped = YES;` and this will also enable TMS tiling. Good work though, this repo really needs TMS support.

**Comment by adam-aerobotics** [comment]
Is there any update on this? We need TMS tile support, and ideally it would be nice if this was standard in the library.

**Comment by christopherdro** [comment]
Superseded by https://github.com/react-native-community/react-native-maps/pull/2732

**Pull request closed without merging**
