### PR TITLE
Remove componentWillUpdate

### PR DESCRIPTION
**Pull request by Taym95**
### Does any other open PR do the same thing?

No similar PR.

### What issue is this PR fixing?

#2843

### CODE REVIEW

**Comment by rborn** [comment]
@Taym95 travis isn't happy :)

Did you test? works good? 🤗

**Comment by jramalho** [comment]
you can use null instead of prevState just to please the Travis linter.

**Comment by jramalho** [comment]
omg this linter is so boring (just kidding, we need it ahah)
you can call the getSnapshotBeforeUpdate like this
``` javascript
getSnapshotBeforeUpdate(prevProps) {
```

and componentDidUpdate like this
``` javascript
componentDidUpdate(prevProps, null, snapshot) 
```
and you can fill the const b with snapshot.region (but you have to test it)
``` javascript
const b = snapshot.region
```

**Comment by Taym95** [comment]
Thanks, I will make the changes and test them.

**Comment by rborn** [comment]
@Taym95 all good? let me know and we merge 🤗

**Comment by jramalho** [comment]
Hello. Tested it here. Works like a charm. Nice work @Taym95 .

**Comment by brownieboy** [comment]
Be warned, if you're not passing in **region** as a prop to your MapView, then you'll get a yellow-screen warning that getSnapshotBeforeUpdate must return a value or null but it actually returned undefined.

FYI, **region** is not actually a mandatory prop.  You could provide **initialRegion** instead, which is what I was doing.  When I switched the prop to **region** the warning went away.

**Pull request merged**
