### PR TITLE
Upgrade react-native to 0.59.3

### PR DESCRIPTION
**Pull request by friederbluemle**
### Does any other open PR do the same thing?

No

### What issue is this PR fixing?

This updates the `react-native` dependency in the example project from `0.54` to the latest version `0.59.3`.

### How did you test this PR?

Tested on:

- Android Emulator
- Android Device (Xiaomi A1)
- iOS Simultor (iPhone X)
- iOS Device (iPhone 8)

### CODE REVIEW

**Comment by rborn** [comment]
@friederbluemle ❤️

Could you try to update travis config to node 10 maybe it builds 🤗

**Comment by friederbluemle** [comment]
@rborn - Update to 8 was enough to make it pass. Please let me know if you prefer it to be set to 10 (it would be my preference too, since it's the current LTS version).

**Comment by friederbluemle** [comment]
We could also set it to `lts/*`, as explained here: https://docs.travis-ci.com/user/languages/javascript-with-nodejs/

**Comment by rborn** [comment]
@friederbluemle go for it 🤗

**Comment by friederbluemle** [comment]
@rborn - `lts/*` works well. It installs the latest long term support version (`v10.15.3`) 👌

**Comment by termux-io** [comment]
[:ux:](https://patch-diff.githubusercontent.com/raw/react-native-community/react-native-maps/pull/2862.diff)

**Comment by termux-io** [comment]
https://patch-diff.githubusercontent.com/raw/react-native-community/react-native-maps/pull/2862.diff

**Pull request merged**
