### PR TITLE
Update settings.gradle

### PR DESCRIPTION
**Pull request by njho**
Name change required in order to compile project

### CODE REVIEW

**Comment by rborn** [comment]
@njho thanks for the PR, could you please explain why we need this change?  What's the case when it doesn't compile?

**Comment by alvelig** [comment]
Neither am I sure about why we need that.

**Comment by rborn** [comment]
@njho please let us know why is this needed, what made you create this PR. Thank you.

**Comment by rborn** [comment]
@christocracy any thoughts about this ? (I think you have way better knowledge of gradle than me 🤗 ) 🐽

**Comment by christopherdro** [comment]
This settings.gradle is specific to the example project in the repo. With these changes, we would also need to following: https://github.com/react-native-community/react-native-maps/blob/00552eaa37b8b0fa459dba7c84aa5c92effa17c6/example/android/app/build.gradle#L130

We could clean things up with a bit with the example project and move the .gradle files out of the root directory.

**Pull request closed without merging**
