### PR TITLE
Google Maps TMS URL tile support

### PR DESCRIPTION
**Pull request by arosendorff**
### Does any other open PR do the same thing?

https://github.com/react-native-community/react-native-maps/pull/2118 
This PR has merge conflicts and has appeared to have stalled.

### What issue is this PR fixing?

None

### How did you test this PR?

1. Set up a simple tile server serving two different tiles, one with the normal XYZ coordinate, and another with the inverted Y value.
2. Implement <UrlTile> with and then without `flipY` to ensure that the correct tile is displayed, and both in the same place.

This has been tested on iOS simulator, and Android and iOS devices.

### CODE REVIEW

**Comment by arosendorff** [comment]
Hi there, for our app we forked react-native-maps to allow use to display TMS tiles (origin coordinate is at the bottom right instead of the top left) using the Google Maps <UrlTile> component and thought it might be useful to merge into the base repo!

**Comment by rborn** [comment]
LGTM  @alvelig @christopherdro  🐽

**Comment by christopherdro** [comment]
@arosendorff Thank you for this. Any chance you add the recommendation from the other PR to add support for iOS as well? `self.tileOverlay.geometryFlipped = YES`

**Comment by arosendorff** [comment]
@christopherdro Yeah I can add that quickly!

**Comment by arosendorff** [comment]
@alvelig @christopherdro I have updated the PR to include the flip for Apple Maps. Let me know if it all looks good to you!

**Comment by sinodko** [comment]
hello @arosendorff I can see that your PR has really close to the issue that I'm trying to solve right now. Please, could you take a look at #2733 . Thank you so much!

**Pull request merged**
