### PR TITLE
#3025 Fixes for polygon custom styles (fillColor, stokeColor, stokeWidth) not being applied on iOS devices when provider is Google maps.

### PR DESCRIPTION
**Pull request by BeckyWu220**
Taking https://github.com/react-native-community/react-native-maps/issues/3025#issuecomment-522968087 as a reference. Apply `fillColor`, `stokeColor` and `stokeWidth` to polygons after the layout is calculated. 

### Does any other open PR do the same thing?

A few related issues (https://github.com/react-native-community/react-native-maps/issues/3025#issuecomment-522968087, https://github.com/react-native-community/react-native-maps/issues/2867#issuecomment-573739457 ) were brought up and some comments indicated some temporary fix. However, no PR was found.

### What issue is this PR fixing?
This issue was found while testing GeoJSON. In `Geojson` component, I passed in multiple style related props, `fillColor`, `strokeColor`, and `strokeWidth`. However, in iOS simulator, I could only see the default style (purple with opacity) being applied when using Google maps. 
```
<Geojson 
    geojson={geoJsonData} 
    strokeColor="rgba(255, 0, 0, 0.7)"
    fillColor="rgba(0, 255, 0, 0.4)"
    strokeWidth={3}
/>
```
As the screenshot below.
Simulator Screen Shot - iPhone X - 2020-02-26 at 14 34 32

Related issues found in repo.
https://github.com/react-native-community/react-native-maps/issues/3025#issuecomment-522968087, https://github.com/react-native-community/react-native-maps/issues/2867#issuecomment-573739457

### How did you test this PR?

Tested on both iOS and Android simulator. Screenshots attached. `geoJsonData` used in the code snippet below is from Google office documentation. https://developers.google.com/maps/documentation/javascript/datalayer#googlejson
```
<Geojson 
    geojson={geoJsonData} 
    strokeColor="rgba(255, 0, 0, 0.7)"
    fillColor="rgba(0, 255, 0, 0.4)"
    strokeWidth={3}
/>
```
Screenshot_1582755900
Simulator Screen Shot - iPhone X - 2020-02-26 at 14 26 08

### CODE REVIEW

**Comment by rborn** [comment]
@BeckyWu220 thank you so much for this PR ❤ 
Is this something it can be used in Apple maps too ? So we have a full cross-provider compatibility or they are not supported by apple maps?

**Comment by BeckyWu220** [comment]
@rborn Hi! This issue was only found on Google maps. Apple maps doesn't have the same issue detected. Thanks!

**Comment by rborn** [comment]
@BeckyWu220 so it works fine in Apple maps without this PR ?

**Comment by BeckyWu220** [comment]
@rborn Yes. Apple map works fine without this PR.

**Comment by rborn** [comment]
@BeckyWu220 great,  thank you 😻

**Comment by BeckyWu220** [comment]
@rborn You are welcome! Great work in maintaining the great library. Thanks!

**Comment by dcosmin2003** [comment]
Hello, I updated the library but I still have this bug :(
From time to time, the polygons are in purple instead of the correct colours.

**Comment by dcosmin2003** [comment]
Something I forgot to mention: I'm using Polygon, not Geojson.

**Pull request merged**
