### PR TITLE
Add compass location offsets for iOS maps

### PR DESCRIPTION
**Pull request by lijason103**
### Does any other open PR do the same thing?

No.

### What issue is this PR fixing?

Adding compass x and y offsets in iOS maps to allow repositioning stock compass
#576  

### How did you test this PR?

-Followed [doc](https://github.com/react-community/react-native-maps/blob/master/docs/mapview.md) format.
-iOS simulator
-Apple Maps

### CODE REVIEW

**Comment by cmbasnett** [comment]
Let's please merge this into master as soon possible!

**Comment by SavageWilliam** [comment]
Will be v useful

**Comment by danoszz** [comment]
Could this be merged in to master? Very helpful feature 🌟

**Comment by rborn** [comment]
@lijason103 any chance to fix the conflict so we can merge ? ❤️

**Comment by lijason103** [comment]
@rborn fixed

**Pull request merged**
