### PR TITLE
Update heatmaps

### PR DESCRIPTION
**Pull request by hubConnect**
I've updated the Heatmaps pull request #240 to work with the current version of react-native-maps. 
@christopherdro You requested the merge conflicts be resolved in the old pull request, would you care to review these changes?

### CODE REVIEW

**Comment by mickadoua** [comment]
still  doesn't work for me 

what i did

````
npm uninstall react-native-maps --save
npm install https://github.com/airbnb/react-native-maps#pull/1549/head --save
``````

on MapScreen.js 
`<MapView.Heatmap points={this.state.markers} /> `

and the error 
> Warning: React.createElement: type is invalid -- expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in.

>Check your code at MapHeatmap.js:42.

Here the render Fucntion 

```
  render() {
    const AIRMapHeatmap = this.getAirComponent();    //return   undefined 
    return <AIRMapHeatmap points={this.getSanitizedPoints()} />;
  }

```

**Comment by zolrath** [comment]
@mickadoua Hm, this pull request covers Apple Maps on iOS and Google Maps on Android. You're using iOS Google Maps?

Also just to be sure, is `AIRGooglzMapHeatMap` a typo? `AIRGoogleMapHeatMap` would be autogenerated I'd think as AIRGooglz doesn't appear in the code anywhere from what I can see.

**Comment by mickadoua** [comment]
Sorry for AIRGooglzMapHeatMap
Its AIRGoogleMapHeatMap or course 

Yes i use Google map on Ios 
I will try with Apple plan

**Comment by mickadoua** [comment]
thanks for your answer, 
so on IOS without Google Maps, 
>  Warning: Native component for "AIRMapHeatmap" does not exist

on android, 




here is my code

```
this.state = {
    markers: [{
                id: 1,
                latitude: 48.825898,
                longitude: 2.259494,
                weight: 10
            }
...
}
<MapView 
   //provider={PROVIDER_GOOGLE}  
   region={this.state.region}  
>
      <MapView.Heatmap points={this.state.markers} />
</MapView>
```
Do you have a working project  ?

**Comment by christopherdro** [comment]
Thank you for putting this together! I look forward to seeing other developers give this a shot and report back if it worked for them.

Can you change the prefix of `DTM` to `AirMap` or something similiar to match the rest of the code base?

**Comment by mickadoua** [comment]
here some new information with  remote debugger

**TEST 1**
#### Map View  
```
<MapView 
   //provider={PROVIDER_GOOGLE}  
   region={this.state.region}  
>
      <MapView.Heatmap points={this.state.markers} />
</MapView>
```
debug result  file : https://github.com/airbnb/react-native-maps/blob/2af950fb1669de3649d81b7881df12c913e3f9cb/lib/components/decorateMapComponent.js#L46-L70
image

**TEST 2**
#### Map View  
```
<MapView 
   provider={PROVIDER_GOOGLE}  
   region={this.state.region}  
>
      <MapView.Heatmap points={this.state.markers} />
</MapView>
```
debug result  file : https://github.com/airbnb/react-native-maps/blob/2af950fb1669de3649d81b7881df12c913e3f9cb/lib/components/decorateMapComponent.js#L46-L70

image

in the both case, HeatMap doesn't work

**Comment by zolrath** [comment]
@mickadoua I've put an example project using this pull request here: https://github.com/zolrath/maptest

@christopherdro The final component is named AIRMapsHeatmap but DTMHeatmaps is a third party library we're pulling in for this. Would AIRMapsDTMHeatmapRenderer etc be appropriate to keep the original authors prefix while ensuring we don't get clashes with other libraries by appending AIRMaps? Let us know what you'd like and we'll proceed!

**Comment by hubConnect** [comment]
@christopherdro DTM naming has been updated to AIRMapDTM

**Comment by zolrath** [comment]
@mickadoua  @christopherdro Did the example project work for you to show the functionality of the Heatmap? Would love to see this feature merged in!

**Comment by hubConnect** [comment]
I second this with an orange thumb or two.

**Comment by plouh** [comment]
By the way, there is brand new [google-maps-ios-utils](https://github.com/googlemaps/google-maps-ios-utils) support library that implements heatmaps over google maps as well so I suggest adding support for google maps heatmaps in iOS also.

I did my own version of the heatmap support without first looking at the pull requests so I missed this one and based my work on that one instead.  

I would add at least opacity and radius parameters to the heatmap as they are trivial, but google maps also supports custom gradients that I'd like to have support also.

**Comment by zolrath** [comment]
@ploluh If you would like to merge our efforts I'd certainly be interested.  I think the important thing here is for the community to finally have Heatmap support in react-native-maps.

**Comment by zolrath** [comment]
@plouh If you would like to merge our efforts I'd certainly be interested.  I think the important thing here is for the community to finally have Heatmap support in react-native-maps.

**Comment by lfkwtz** [comment]
+1 interested in heatmap support for google maps

**Comment by AngelVenchev** [comment]
Hey, any progress on this? What is needed to get this merged?

**Comment by belzm** [comment]
Has any further progress been made on this?

**Comment by YeshanJay** [comment]
Any update on this? Would be great if this feature is merged.

**Comment by jakoblorz** [comment]
Most recent and promising activity on this topic seems to be in PR #2241

**Comment by christopherdro** [comment]
Please try https://github.com/react-native-community/react-native-maps/pull/2960

**Comment by christopherdro** [comment]
Closing for https://github.com/react-native-community/react-native-maps/pull/2960

**Pull request closed without merging**
