### PR TITLE
Expose GoogleMaps iOS SDK icon property to improve Marker rendering performance

### PR DESCRIPTION
**Pull request by victormartingarcia**
### Does any other open PR do the same thing?

This PR is based on https://github.com/react-native-community/react-native-maps/pull/1491 changeset

It hasn't been merged (presumably unsolved conflicts), but I see Marker **tracksViewChange** property is already exposed on master branch, so it makes sense to expose Marker **icon** property as well

### What issue is this PR fixing?

Rendering Markers on iOS using Google Maps have some performance issues (see #2616, #1031, #2575 ..)
Some people have solved that with some extra logic tweaking **tracksViewChange** property (see https://github.com/react-native-community/react-native-maps/issues/1031#issuecomment-378881118 ), but [as Google explains in the SDK docs](https://developers.google.com/maps/documentation/ios-sdk/marker#use_the_markers_icon_property), for static Markers is much better to use icon property.

Using this icon property solves all iOS performance issues, making the map much smoother :)

### How did you test this PR?

This fix has been tested on iPhone simulator and real devices (iPhone 6 and iPhone X) with extremely good results. 

On Android, `icon` property works like `image` property, as Android SDK does not differentiate between static image Markers and View-based ones

### Example
```
<Marker
    coordinate={{
        latitude: this.state.myLatitude,
        longitude: this.state.myLongitude
    }}
    icon={require('../Images/myIcon.png')}
/>
```

### CODE REVIEW

**Comment by rborn** [comment]
Thanks for the PR ❤️

I wonder of we could unify the `icon/image` props between the platforms? so we use one name only? Or on iOS we can use both `image` and `icon` ?

@alvelig thoughts ? and 🐽
LGTM

**Comment by victormartingarcia** [comment]
@rborn on iOS you can use both `image` and `icon` for different purposes (icon only works for static images)

Let me check if I can make it compatible with android, for not having to differentiate it on Marker props

**Comment by victormartingarcia** [comment]
I managed to support `icon` property on android as well, so no need to differentiate platform on Marker definition ;)

Using `icon` on android is exactly the same as using `image`, as android Google Maps SDK does not differentiate between static image Markers and View-based ones

**Comment by rborn** [comment]
@victormartingarcia looks good, thanks.
One question though: is there anything we need to do to handle `@2x/@3x` images? How do the marker decide the size of the icon? (maybe we should add some docs saying what's the ideal marker icon size if google specifies something about it?)

**Comment by victormartingarcia** [comment]
> One question though: is there anything we need to do to handle `@2x/@3x` images? 

I've tested and `@2x/@3x` images are handled automatically 👍 

> How do the marker decide the size of the icon? 

Just like with `image` property, the Marker takes picture size by default. 

> (maybe we should add some docs saying what's the ideal marker icon size if google specifies something about it?)

Haven't found anything about Marker size in Google Maps SDKs docs...

**Comment by rborn** [comment]
@victormartingarcia let's wait a little for @alvelig to reply (if) and then we'll merge 🎉

**Comment by christopherdro** [comment]
Related to https://github.com/react-native-community/react-native-maps/pull/1491

**Comment by christopherdro** [comment]
I'm not sure why this wasn't caught in the tests that ran on this PR but I am following up with the following https://github.com/react-native-community/react-native-maps/pull/2651

**Pull request merged**
