### PR TITLE
Android cleanup: little improved way of getting SDK values

### PR DESCRIPTION
**Pull request by yeomann**
just a little improved version rather then many explicit def for each value. hence, less cluttering. also made the react-native package to get the dynamic versions as well

Android Target API Level 26 will be required in August 2018.
https://android-developers.googleblog.com/2017/12/improving-app-security-and-performance.html

I was going to write 26 but Since we are already using latest Gradle, Therefore I wrote target values of 27 instead of 25.

And the React Native team is already working on this:
facebook/react-native#18095
facebook/react-native#17741

### Does any other open PR do the same thing?

Not that I could find.

### What issue is this PR fixing?

its a android cleanup for less `def` variables mainly but also addressing SDK changes
Android Target API Level 26 will be required in August 2018.
https://android-developers.googleblog.com/2017/12/improving-app-security-and-performance.html

### How did you test this PR?

Real device and simulator both Android and IOS, with (SDK 23 real device), 25 and 26 on Simulators

### CODE REVIEW

**Comment by salah-ghanim** [comment]
how come there is no activity here, this is blocking our Android SDK update

**Comment by alvelig** [comment]
I'm not sure we need this change. For now versions are in a separate place altogether. @rborn what do you think?

**Comment by rborn** [comment]
@alvelig not sure tbh, my android-fu is very rusty :(

**Comment by friederbluemle** [comment]
@alevig @rborn - This can safely be closed, as this (and more) was added in #2720, #2727, and #2765

**Pull request closed without merging**
