### PR TITLE
GoogleMaps 2.5.0 compatibility. Remove legalnotice. It's deprecated by Google

### PR DESCRIPTION
**Pull request by kesha-antonov**

### CODE REVIEW

**Comment by kesha-antonov** [comment]
https://developers.google.com/android/reference/com/google/android/gms/common/GooglePlayServicesUtil#getOpenSourceSoftwareLicenseInfo(android.content.Context)

screen shot 2017-11-03 at 21 43 44

**Comment by kesha-antonov** [comment]
And after this I think we should revert this PR (https://github.com/airbnb/react-native-maps/commit/5edaaf47c2132d1283e4453de7e7fd61d6434f69) since it's not needed anymore. Right?

**Comment by rborn** [comment]
@kesha-antonov thanks a lot for this PR, is this still something we need?

**Comment by christopherdro** [comment]
Looks like another similar PR was already merged in. https://github.com/react-native-community/react-native-maps/pull/1612

**Pull request closed without merging**
